# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frame1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(460, 100)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.widget = QtWidgets.QWidget(Frame)
        self.widget.setGeometry(QtCore.QRect(10, 10, 100, 80))
        self.widget.setStyleSheet("background-color: rgb(147, 147, 147);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(140, 10, 311, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(140, 45, 311, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(140, 70, 311, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#00007f;\">RENOVA SG5-1ETDB(ICTDW)</span></p></body></html>"))
        self.label_2.setText(_translate("Frame", "смена А, 12 апреля 2024 г"))
        self.label_3.setText(_translate("Frame", "номера с 1 по 350"))
